### ISSUE TITLE
ApricotVector ".at()" function

### ISSUE THREAD

**Issue by KadynCBR** [KadynCBR/Apricot-Linear-Library#11]
Right now, ApricotVectors are used as the basis for everything. 
in order to iterate them we have to get their vectors and store them in another vector variable.
ie)
`ApricotVector av = A.mat.at(i);`
`std::vector<double> av_vec = av.GetVector();`
`for (unsigned int j = 0; j < av_vec.size(); j++) {`
 `output << av_vec.at(j) << " ";`
`}`

This is memory intensive, tasking, messy and quite frankly _**not dope.**_
I propose using a  ".at()" function in which 
I can reference individual elements of an ApricotVector using only 

`ApricotVector av = A.mat.at(i);`
`for (unsigned int j = 0; j < av.size(); j++) {`
`output << av.at(j);`
`}`

This of course would mean the implementation of a ".size()" function in order to work as intended above.

**Comment by omegabytes** [comment]
->
